name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest -v tests

      - name: Run tests with code coverage
        run: |
          pip install pytest-cov
          python -m pytest --cov=./ --cov-report=xml tests

      - name: Generate coverage comment 
        run: | 
          pip install pytest-coverage-comment python -m pytest_coverage_comment --file cov.xml
  
